ALTER TABLE users ADD COLUMN permission_popupSubmission BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN banned BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN linkOrder INTEGER;
ALTER TABLE users ADD COLUMN embedOrder INTEGER;
ALTER TABLE users ADD COLUMN label TEXT;