ALTER TABLE matches ADD COLUMN league_id TEXT NULL;
ALTER TABLE matches ADD COLUMN slug TEXT NOT NULL;
ALTER TABLE matches ADD COLUMN league_slug TEXT NOT NULL;
ALTER TABLE matches ADD COLUMN sport_slug TEXT NOT NULL;
